services:
  - type: web
    name: cambodia-law-bot
    env: python
    plan: free
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "python bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GAS_URL
        sync: false
      - key: ADMIN_IDS
        sync: false
